### ISSUE TITLE
Styling issues after Bootstrap 5 update

### ISSUE THREAD

**Issue by MarcinOsiadacz** [tsjensen/fuse-core#2]
Hi!

I've noticed 2 issues with styling after Bootstrap 5 update.

1. Header containing site.name is no longer bold, because class name has been changed in Bootstrap 5. You can fix it by replacing _font-weight-bold_ class with _fw-bold_.
2. Anchor links in footer are now underlined. Quick fix will be updating theme.scss by adding _text-decoration: none;_ for footer anchor links not only on hover (as it is currently), but also above.

I've tested these fixes locally. I can create a Pull Request with these changes if you like.

Very nice theme by the way ;)

**Comment by tsjensen** [comment]
Thank you for bringing this up, well observed!

If you can do a PR, that'd be great. :-)

**Comment by MarcinOsiadacz** [comment]
Sure thing, just add me as a collaborator ;)

**Comment by tsjensen** [comment]
In this project, pull requests are open to all - you can just go ahead!

**Comment by tsjensen** [comment]
Fixed by #3 - thanks a lot @MarcinOsiadacz
